function TermNames() {

	this.PropertyStreetNumber = "S1_StreetNumber";
	this.PropertyStreetName = "S1_StreetName";
	this.PropertyStreetAddress = "S1_StreetAddress";
	this.PropertyAddressLine2 = "S1_ApartmentNumber";
	this.PropertyCity = "S1_City";
	this.PropertyState = "S1_State";
	this.PropertyZipCode = "S1_Zipcode";
	this.InsuredByCorporation = "S1_OwnedBy";
	this.InsuredName = "S1_EntityName";
	this.ApplicantFirstName = "S1_FirstName";
	this.ApplicantLastName = "S1_LastName";
	this.InsuredFirstName = "S1_FirstName";
	this.InsuredLastName = "S1_LastName";
	this.PropertyUsage = "S1_PropertyUsage";
	this.PropertyOccupancy = "S1_PropertyOccupancy";
	this.MonthsUnoccupied = "S1_TimeUnoccupied";

	this.NumberOfMonthsUnoccupied = "S1_NumberOfMonthsUnoccupied";
	this.ShortTermRental = "S1_ShortTermRental";
	this.SingleOccupancy = "S1_SingleOccupancy";
	this.StudentOccupancy = "S1_StudentOccupancy";
	this.PropertyManagerType = "S1_PropertyManagerType";
	this.PropertyManagerAddressLine1 = "S1_PropertyManagerAddressLine1";
	this.PropertyManagerAddressLine2 = "S1_PropertyManagerAddressLine2";
	this.PropertyManagerCity = "S1_PropertyManagerCity";
	this.PropertyManagerState = "S1_PropertyManagerState";
	this.PropertyManagerZip = "S1_PropertyManagerZip";

	this.CurrentInsurance = "S2_CurrentInsurance"; //Note: Not an EZQuote TermName
	this.PriorCarrierNumber = "S2_InsuranceAgencies";
	this.PriorCarrierOther = "S2_PriorCarrierOther";
	this.PriorExpirationDate = "S2_PolicyExpiration";
	this.NumberOfClaims = "S2_NumberOfClaims";
	this.PriorCoverageA = "S2_DwellingCoverage";
	this.LossDate1 = "S2_2_DateOfLoss:1";
	this.LossAmount1 = "S2_2_LossAmountPaid:1";
	this.LossType1 = "S2_2_LossType:1";
	this.LossCatIndicator1 = "S2_2_LossCatastrophe:1";
	this.LossDescription1 = "S2_2_LossDescription:1";
	this.LossDate2 = "S2_2_DateOfLoss:2";
	this.LossAmount2 = "S2_2_LossAmountPaid:2";
	this.LossType2 = "S2_2_LossType:2";
	this.LossCatIndicator2 = "S2_2_LossCatastrophe:2";
	this.LossDescription2 = "S2_2_LossDescription:2";
	this.LossDate3 = "S2_2_DateOfLoss:3";
	this.LossAmount3 = "S2_2_LossAmountPaid:3";
	this.LossType3 = "S2_2_LossType:3";
	this.LossCatIndicator3 = "S2_2_LossCatastrophe:3";
	this.LossDescription3 = "S2_2_LossDescription:3";
	this.HomeStyle = "S3_StructureType";
	this.ConstructionYear = "S3_YearBuilt";
	this.SquareFootUnderRoof = "S3_LivingArea";
	this.NumberOfStories = "S3_NumberOfStories";
	this.StructureType = "S3_HomeType";
	this.ConstructionYearRoof = "S3_RoofInstalled";
	this.RoofCoveringType = "S3_RoofType";
	this.RoofGeometryType = "S3_RoofShape";
	this.GarageSize = "S3_2_GarageSize"; //Note: Not an EZQuote TermName
	this.GarageType = "S3_2_GarageType";
	this.SquareFootUnderRoofGarage = "S3_2_GarageSizeSqFt";
	this.FoundationType = "S3_2_FoundationType";
	this.ConstructionType = "S3_2_ConstructionType";
	this.Cladding = "S3_2_CladdingType";
	this.MasonryVeneerPercentage = "S3_2_MasonryVeenerType";
	this.NumberOfKitchens = "S3_3_NumberOfKitchens";
	this.KitchenQuality = "S3_3_KitchenGrade";
	this.NumberOfFullBaths = "S3_3_NumberOfFullBathrooms";
	this.FullBathQuality = "S3_3_FullBathroomGrade";
	this.NumberOfHalfBaths = "S3_3_NumberOfHalfBathrooms";
	this.HalfBathQuality = "S3_3_HalfBathroomGrade";
	this.NumberOfFireplaces = "S3_3_NumberOfFireplaces";
	this.HeatPump = "S3_3_HeatPump";
	this.CentralAir = "S3_3_CentralAir";
	this.WoodStove = "S3_3_WoodStove";
    this.WallHeight = "S3_3_WallHeight";
    this.FloorCoveringType = "S3_3_FloorCoveringType";
	this.StepsRisersWithoutHandrails = "S3_3_StepsRisersWithoutHandrails";
	this.NumberOfStepsRisersWithoutHandrails = "S3_3_NumberOfStepsRisersWithoutHandrails";
	this.HomeFeatures1 = "";
	this.HomeFeatures1SquareFeet = "";
	this.HomeFeatures2 = "";
	this.HomeFeatures2SquareFeet = "";
	this.HomeFeatures3 = "";
	this.HomeFeatures3SquareFeet = "";

	//Note EZQuote TermNames//
	/**/this.HomeFeaturesWoodDeck = "S3_4_WoodDeck";
	/**/this.HomeFeaturesWoodDeckSF = "S3_4_WoodDeckSqFt";
	/**/this.HomeFeaturesCompositeDeck = "S3_4_CompositeDeck";
	/**/this.HomeFeaturesCompositeDeckSF = "S3_4_CompositeDeckSqFt";
	/**/this.HomeFeaturesOpenPorch = "S3_4_OpenPorch";
	/**/this.HomeFeaturesOpenPorchSF = "S3_4_OpenPorchSqFt";
	/**/this.HomeFeaturesGreenhouse = "S3_4_Greenhouse";
	/**/this.HomeFeaturesGreenhouseSF = "S3_4_GreenhouseSqFt";
	/**/this.HomeFeaturesScreenedPorch = "S3_4_ScreenedPorch";
	/**/this.HomeFeaturesScreenedPorchSF = "S3_4_ScreenedPorchSqFt";
	/**/this.HomeFeaturesOpenBreezeway = "S3_4_OpenBreezeway";
	/**/this.HomeFeaturesOpenBreezewaySF = "S3_4_OpenBreezewaySqFt";
	/**/this.HomeFeaturesScreenedBreezeway = "S3_4_ScreenedBreezeway";
	/**/this.HomeFeaturesScreenedBreezewaySF = "S3_4_ScreenedBreezewaySqFt";
	////////////////////////////

	this.Pets = "S3_5_DogOwner";
	this.Dogs = "S3_5_DogBreeds";
	this.DistanceFireHydrant = "S3_5_DistanceToFireHydrant";
	this.PoolType = "S3_5_SwimmingPool";
	this.PoolFence = "S3_5_PropertyFenced";
	this.DivingBoardSlide = "S3_5_BoardOrSlide";
	this.DivingBoardSlide2 = "S3_5_BoardOrSlide";
	this.ImmovablePoolLadder = "S3_5_ImmovableLadder";
	this.MultiPolicy = "S4_MultiPolicy";
	this.AutoPolicyNumber = "S4_AutoPolicyNumber";
	this.PrimeTimeDiscount = "S4_PrimeTimeDiscount";

	this.WindMitigationForm = "S4_WindMitigationForm";
    this.BCEquivalent = "S4_BCEquivalent";
    this.RoofDeckAttachmentType = "S4_RoofDeckAttachmentType";
    this.RoofWallConnectionType = "S4_RoofWallConnectionType";
    this.SecondaryWaterResistance = "S4_SecondaryWaterResistance";
    this.OpeningProtectionTypeWLMForm = "S4_OpeningProtectionTypeWLMForm";

	this.Insured1BirthDate = "S4_Insured1BirthDate";
	this.Insured1SSN = "S4_Insured1SSN";
	//this.Insured1SSNRequiredIndicator = "S4_Insured1SSN"; //Note: not a form on front-end
	this.InsuredEmailAddress = "S4_InsuredEmailAddress";
	this.FireAlarm = "S4_FireAlarmLocation";
	this.BurglarAlarm = "S4_BurglarAlarmLocation";
	this.Sprinklers = "S4_SprinklersLocation";
	this.AcceptLegalTerms = "S4_AcceptLegalTerms"; //Note: not an EZQuote TermName

	this.CoverageADisplay = "S5_Dwelling";
	this.CoverageA = "S5_Dwelling";
	this.AdditionalAmountsOfInsurance = "S5_AdditionalInsuranceLimits";
	this.PersonalPropertyReplacementCost = "S5_PersonalPropertyReplacementCost";
	this.OptionCoverageB = "S5_OtherStructures";
	this.CoverageB = "S5_OtherStructures";
	this.OptionCoverageD = "S5_LossOfUse";
	this.CoverageD = "S5_LossOfUse";
	this.OptionCoverageC = "S5_PersonalProperty";
	this.CoverageC = "S5_PersonalProperty";
	this.ReplacementCostRounded = "S5_ReplacementCostRounded";
	this.ReplacementCost = "S5_SettlementType";
	this.EarthquakeCoverage = "S5_EarthquakeCoverage";
	this.IdentityFraudCoverage = "S5_IdentityFraudCoverage";
	this.WaterBackupCoverage = "S5_OverflowCoverage";
	this.JewelrySpecialLimits = "S5_JewelryCoverage";
	this.MechanicalBreakdownCoverage = "S5_MechanicalBreakdownCoverage";
	this.PersonalInjuryCoverage = "S5_PersonalInjuryCoverage";
	this.TheftCoverage = "S5_TheftCoverage";
	this.LossAssessmentCoverage = "S5_LossAssessment";
	this.IncreasedOrdinanceLimit = "S5_OrdinanceCoverage";
	this.AllOtherPerilsDeductible = "S5_RegularLoss";
	this.HurricaneDeductible = "S5_HurricaneDeductible";
	this.WindHailDeductible = "S5_WindHailDeductible";
	//this.HurricaneDeductible = "";
	this.CoverageE = "S5_PersonalLiability";
	this.CoverageL = "S5_PersonalLiability";
	this.CoverageF = "S5_MedicalPayments";
	this.CoverageM = "S5_MedicalPayments";


}
