const BlockCodes = {

	PropertyStreetNumber: {},
	PropertyStreetName: {},
	PropertyStreetAddress: {},
	PropertyAddressLine2: {},
	PropertyCity: {},
	PropertyState: {},
	PropertyZipCode: {},
	InsuredByCorporation: {},
	InsuredName: {},
	ApplicantFirstName: {},
	ApplicantLastName: {},
	InsuredFirstName: {},
	InsuredLastName: {},
	PropertyUsage: {'100-200': '111',
					'100-300': '122'},
	PropertyOccupancy: {},
	MonthsUnoccupied: {'3': '120'},

	NumberOfMonthsUnoccupied: {},
	ShortTermRental: {},
	SingleOccupancy: {},
	StudentOccupancy: {},
	PropertyManagerType: {},
	PropertyManagerAddressLine1: {},
	PropertyManagerAddressLine2: {},
	PropertyManagerCity: {},
	PropertyManagerState: {},
	PropertyManagerZip: {},

	CurrentInsurance: {'0': '130'}, //Note: Not an EZQuote TermName
	PriorCarrierNumber: {},
	PriorCarrierOther: {},
	PriorExpirationDate: {},
	NumberOfClaims: {'3': '211'},
	PriorCoverageA: {'4': '211'},
	LossDate1: {},
	LossAmount1: {},
	LossType1: {},
	LossCatIndicator1: {},
	LossDescription1: {},
	LossDate2: {},
	LossAmount2: {},
	LossType2: {},
	LossCatIndicator2: {},
	LossDescription2: {},
	LossDate3: {},
	LossAmount3: {},
	LossType3: {},
	LossCatIndicator3: {},
	LossDescription3: {},
	HomeStyle: {},
	ConstructionYear: {},
	SquareFootUnderRoof: {},
	NumberOfStories: {},
	StructureType: {'102': '212',
					'103': '213',
					'104': '213'},
	ConstructionYearRoof: {},
	RoofCoveringType: {},
	RoofGeometryType: {},
	GarageSize: {}, //Note: Not an EZQuote TermName
	GarageType: {},
	SquareFootUnderRoofGarage: {},
	FoundationType: {},
	ConstructionType: {},
	Cladding: {},
	MasonryVeneerPercentage: {},
	NumberOfKitchens: {},
	KitchenQuality: {},
	NumberOfFullBaths: {},
	FullBathQuality: {},
	NumberOfHalfBaths: {},
	HalfBathQuality: {},
	NumberOfFireplaces: {},
	HeatPump: {},
	CentralAir: {},
	WoodStove: {'100': '0'},
    WallHeight: {},
    FloorCoveringType: {},
	StepsRisersWithoutHandrails: {},
	NumberOfStepsRisersWithoutHandrails: {},
	HomeFeatures1: {},
	HomeFeatures1SquareFeet: {},
	HomeFeatures2: {},
	HomeFeatures2SquareFeet: {},
	HomeFeatures3: {},
	HomeFeatures3SquareFeet: {},

	//Note EZQuote TermNames//
	/**/HomeFeaturesWoodDeck: {},
	/**/HomeFeaturesWoodDeckSF: {},
	/**/HomeFeaturesCompositeDeck: {},
	/**/HomeFeaturesCompositeDeckSF: {},
	/**/HomeFeaturesOpenPorch: {},
	/**/HomeFeaturesOpenPorchSF: {},
	/**/HomeFeaturesGreenhouse: {},
	/**/HomeFeaturesGreenhouseSF: {},
	/**/HomeFeaturesScreenedPorch: {},
	/**/HomeFeaturesScreenedPorchSF: {},
	/**/HomeFeaturesOpenBreezeway: {},
	/**/HomeFeaturesOpenBreezewaySF: {},
	/**/HomeFeaturesScreenedBreezeway: {},
	/**/HomeFeaturesScreenedBreezewaySF: {},
	////////////////////////////

	Pets: {},
	Dogs: {'100': '317'},
	DistanceFireHydrant: {},
	PoolType: {},
	PoolFence: {'200': '313'},
	DivingBoardSlide: {'100': '314'},
	DivingBoardSlide2: {'100': '314'},
	ImmovablePoolLadder: {'100': '316'},
	MultiPolicy: {},
	AutoPolicyNumber: {},
	PrimeTimeDiscount: {},

	WindMitigationForm: {},
    BCEquivalent: {},
    RoofDeckAttachmentType: {},
    RoofWallConnectionType: {},
    SecondaryWaterResistance: {},
    OpeningProtectionTypeWLMForm: {},

	Insured1BirthDate: {},
	Insured1SSN: {},
	//Insured1SSNRequiredIndicator: {}, //Note: not a form on front-end
	InsuredEmailAddress: {},
	FireAlarm: {},
	BurglarAlarm: {},
	Sprinklers: {},
	AcceptLegalTerms: {}, //Note: not an EZQuote TermName

	CoverageADisplay: {},
	CoverageA: {},
	AdditionalAmountsOfInsurance: {},
	PersonalPropertyReplacementCost: {},
	OptionCoverageB: {},
	CoverageB: {},
	OptionCoverageD: {},
	CoverageD: {},
	OptionCoverageC: {},
	CoverageC: {},
	ReplacementCostRounded: {},
	ReplacementCost: {},
	EarthquakeCoverage: {},
	IdentityFraudCoverage: {},
	WaterBackupCoverage: {},
	JewelrySpecialLimits: {},
	MechanicalBreakdownCoverage: {},
	PersonalInjuryCoverage: {},
	TheftCoverage: {},
	LossAssessmentCoverage: {},
	IncreasedOrdinanceLimit: {},
	AllOtherPerilsDeductible: {},
	HurricaneDeductible: {},
	WindHailDeductible: {},
	//HurricaneDeductible: {},
	CoverageE: {},
	CoverageL: {},
	CoverageF: {},
	CoverageM: {}


}

export default BlockCodes