const TermNames = {

	PropertyStreetNumber: "PropertyStreetNumber",
	PropertyStreetName: "PropertyStreetName",
	PropertyStreetAddress: "PropertyStreetAddress",
	PropertyAddressLine2: "PropertyAddressLine2",
	PropertyCity: "PropertyCity",
	PropertyState: "PropertyState",
	PropertyZipCode: "PropertyZipCode",
	InsuredByCorporation: "InsuredByCorporation",
	InsuredName: "InsuredName",
	ApplicantFirstName: "ApplicantFirstName",
	ApplicantLastName: "ApplicantLastName",
	InsuredFirstName: "InsuredFirstName",
	InsuredLastName: "InsuredLastName",
	PropertyUsage: "PropertyUsage",
	PropertyOccupancy: "PropertyOccupancy",
	MonthsUnoccupied: "MonthsUnoccupied",
	PropertyCounty: "PropertyCounty",

	NumberOfMonthsUnoccupied: "NumberOfMonthsUnoccupied",
	ShortTermRental: "ShortTermRental",
	SingleOccupancy: "SingleOccupancy",
	StudentOccupancy: "StudentOccupancy",
	PropertyManagerType: "PropertyManagerType",
	PropertyManagerAddressLine1: "PropertyManagerAddressLine1",
	PropertyManagerAddressLine2: "PropertyManagerAddressLine2",
	PropertyManagerCity: "PropertyManagerCity",
	PropertyManagerState: "PropertyManagerState",
	PropertyManagerZip: "PropertyManagerZip",

	CurrentInsurance: "CurrentInsurance", //Note: Not an EZQuote TermName
	PriorCarrierNumber: "PriorCarrierNumber",
	PriorCarrierOther: "PriorCarrierOther",
	PriorExpirationDate: "PriorExpirationDate",
	NumberOfClaims: "NumberOfClaims",
	PriorCoverageA: "PriorCoverageA",
	LossDate1: "LossDate1",
	LossAmount1: "LossAmount1",
	LossType1: "LossType1",
	LossCatIndicator1: "LossCatIndicator1",
	LossDescription1: "LossDescription1",
	LossDate2: "LossDate2",
	LossAmount2: "LossAmount2",
	LossType2: "LossType2",
	LossCatIndicator2: "LossCatIndicator2",
	LossDescription2: "LossDescription2",
	LossDate3: "LossDate3",
	LossAmount3: "LossAmount3",
	LossType3: "LossType3",
	LossCatIndicator3: "LossCatIndicator3",
	LossDescription3: "LossDescription3",
	HomeStyle: "HomeStyle",
	ConstructionYear: "ConstructionYear",
	SquareFootUnderRoof: "SquareFootUnderRoof",
	NumberOfStories: "NumberOfStories",
	StructureType: "StructureType",
	ConstructionYearRoof: "ConstructionYearRoof",
	RoofCoveringType: "RoofCoveringType",
	RoofGeometryType: "RoofGeometryType",
	GarageSize: "GarageSize", //Note: Not an EZQuote TermName
	GarageType: "GarageType",
	SquareFootUnderRoofGarage: "SquareFootUnderRoofGarage",
	FoundationType: "FoundationType",
	ConstructionType: "ConstructionType",
	Cladding: "Cladding",
	MasonryVeneerPercentage: "MasonryVeneerPercentage",
	NumberOfKitchens: "NumberOfKitchens",
	KitchenQuality: "KitchenQuality",
	NumberOfFullBaths: "NumberOfFullBaths",
	FullBathQuality: "FullBathQuality",
	NumberOfHalfBaths: "NumberOfHalfBaths",
	HalfBathQuality: "HalfBathQuality",
	NumberOfFireplaces: "NumberOfFireplaces",
	HeatPump: "HeatPump",
	CentralAir: "CentralAir",
	WoodStove: "WoodStove",
    WallHeight: "WallHeight",
    FloorCoveringType: "FloorCoveringType",
	StepsRisersWithoutHandrails: "StepsRisersWithoutHandrails",
	NumberOfStepsRisersWithoutHandrails: "NumberOfStepsRisersWithoutHandrails",
	HomeFeatures1: "",
	HomeFeatures1SquareFeet: "",
	HomeFeatures2: "",
	HomeFeatures2SquareFeet: "",
	HomeFeatures3: "",
	HomeFeatures3SquareFeet: "",

	//Note EZQuote TermNames//
	/**/HomeFeaturesWoodDeck: "WoodDeck",
	/**/HomeFeaturesWoodDeckSF: "WoodDeckSqFt",
	/**/HomeFeaturesCompositeDeck: "CompositeDeck",
	/**/HomeFeaturesCompositeDeckSF: "CompositeDeckSqFt",
	/**/HomeFeaturesOpenPorch: "OpenPorch",
	/**/HomeFeaturesOpenPorchSF: "OpenPorchSqFt",
	/**/HomeFeaturesGreenhouse: "Greenhouse",
	/**/HomeFeaturesGreenhouseSF: "GreenhouseSqFt",
	/**/HomeFeaturesScreenedPorch: "ScreenedPorch",
	/**/HomeFeaturesScreenedPorchSF: "ScreenedPorchSqFt",
	/**/HomeFeaturesOpenBreezeway: "OpenBreezeway",
	/**/HomeFeaturesOpenBreezewaySF: "OpenBreezewaySqFt",
	/**/HomeFeaturesScreenedBreezeway: "ScreenedBreezeway",
	/**/HomeFeaturesScreenedBreezewaySF: "ScreenedBreezewaySqFt",
	////////////////////////////

	Pets: "Pets",
	Dogs: "Dogs",
	DistanceFireHydrant: "DistanceFireHydrant",
	PoolType: "PoolType",
	PoolFence: "PoolFence",
	DivingBoardSlide: "DivingBoardSlide",
	DivingBoardSlide2: "DivingBoardSlide2",
	ImmovablePoolLadder: "ImmovablePoolLadder",
	MultiPolicy: "MultiPolicy",
	AutoPolicyNumber: "AutoPolicyNumber",
	PrimeTimeDiscount: "PrimeTimeDiscount",

	WindMitigationForm: "WindMitigationForm",
    BCEquivalent: "BCEquivalent",
    RoofDeckAttachmentType: "RoofDeckAttachmentType",
    RoofWallConnectionType: "RoofWallConnectionType",
    SecondaryWaterResistance: "SecondaryWaterResistance",
    OpeningProtectionTypeWLMForm: "OpeningProtectionTypeWLMForm",

	Insured1BirthDate: "Insured1BirthDate",
	Insured1SSN: "Insured1SSN",
	//Insured1SSNRequiredIndicator: "Insured1SSN", //Note: not a form on front-end
	InsuredEmailAddress: "InsuredEmailAddress",
	FireAlarm: "FireAlarmLocation",
	BurglarAlarm: "BurglarAlarmLocation",
	Sprinklers: "SprinklersLocation",
	AcceptLegalTerms: "AcceptLegalTerms", //Note: not an EZQuote TermName

	CoverageADisplay: "Dwelling",
	CoverageA: "Dwelling",
	AdditionalAmountsOfInsurance: "AdditionalInsuranceLimits",
	PersonalPropertyReplacementCost: "PersonalPropertyReplacementCost",
	OptionCoverageB: "OtherStructures",
	CoverageB: "OtherStructures",
	OptionCoverageD: "LossOfUse",
	CoverageD: "LossOfUse",
	OptionCoverageC: "PersonalProperty",
	CoverageC: "PersonalProperty",
	ReplacementCostRounded: "ReplacementCostRounded",
	ReplacementCost: "SettlementType",
	EarthquakeCoverage: "EarthquakeCoverage",
	IdentityFraudCoverage: "IdentityFraudCoverage",
	WaterBackupCoverage: "OverflowCoverage",
	JewelrySpecialLimits: "JewelryCoverage",
	MechanicalBreakdownCoverage: "MechanicalBreakdownCoverage",
	PersonalInjuryCoverage: "PersonalInjuryCoverage",
	TheftCoverage: "TheftCoverage",
	LossAssessmentCoverage: "LossAssessment",
	IncreasedOrdinanceLimit: "OrdinanceCoverage",
	AllOtherPerilsDeductible: "RegularLoss",
	HurricaneDeductible: "HurricaneDeductible",
	WindHailDeductible: "WindHailDeductible",
	//HurricaneDeductible: "",
	CoverageE: "PersonalLiability",
	CoverageL: "PersonalLiability",
	CoverageF: "MedicalPayments",
	CoverageM: "MedicalPayments"


}

export default TermNames